"""Mock provider — deterministic offline fallback.

Clearly labeled in logs and the /health endpoint. It exists so the product stays
fully navigable (and demoable) when no Gemma runtime is reachable. Every agent
response shape is supported: planner JSON, writer markdown, refiner transforms,
validator/reviewer JSON, exporter summary.
"""
import asyncio
import re
from typing import AsyncIterator

from app.ai.schemas import LLMMessage, LLMResponse

_MARK = "<!-- generated by offline demo provider -->"


def _user_text(messages: list[LLMMessage]) -> str:
    return "\n".join(m.content for m in messages if m.role == "user")


def _system_text(messages: list[LLMMessage]) -> str:
    return "\n".join(m.content for m in messages if m.role == "system")


def _titleize(text: str, fallback: str = "Untitled Document") -> str:
    words = re.sub(r"[^\w\s-]", "", text).strip().split()
    if not words:
        return fallback
    return " ".join(words[:8]).title()


def _field(text: str, name: str, default: str = "") -> str:
    m = re.search(rf"^{name}:\s*(.+)$", text, flags=re.MULTILINE | re.IGNORECASE)
    return m.group(1).strip() if m else default


def _topic_words(text: str, limit: int = 6) -> list[str]:
    stop = {
        "the", "a", "an", "and", "or", "for", "with", "that", "this", "from", "into",
        "document", "write", "create", "generate", "user", "request", "section", "title",
        "path", "goal", "tone", "type", "hint", "none", "extra", "instructions",
    }
    words = [w for w in re.findall(r"[A-Za-z][A-Za-z-]{3,}", text.lower()) if w not in stop]
    seen: list[str] = []
    for w in words:
        if w not in seen:
            seen.append(w)
        if len(seen) >= limit:
            break
    return seen or ["overview", "details", "summary"]


class MockProvider:
    name = "mock"

    def _respond(self, messages: list[LLMMessage]) -> str:
        system = _system_text(messages).lower()
        user = _user_text(messages)
        if "planner agent" in system:
            return self._planner(user)
        if "writer agent" in system:
            return self._writer(user)
        if "refiner agent" in system:
            return self._refiner(user)
        if "validator agent" in system:
            return self._validator(user)
        if "reviewer agent" in system:
            return self._reviewer(user)
        if "exporter agent" in system:
            return self._exporter(user)
        return self._writer(user)

    # -- agent-specific deterministic responses ------------------------------

    def _planner(self, user: str) -> str:
        request = _field(user, "USER REQUEST", user[:200])
        title = _titleize(request)
        topics = _topic_words(request, 4)
        core = [t.title() for t in topics[:2]] or ["Overview", "Details"]
        sections = [
            {"title": "Introduction", "prompt": f"Introduce {title}: purpose, audience, and scope. 2-3 paragraphs."},
            {"title": "Objectives", "prompt": f"State the measurable objectives of {title} as a bullet list."},
            {
                "title": "Scope",
                "prompt": f"Define what is in scope and out of scope for {title}.",
                "children": [
                    {"title": f"{core[0]} Overview", "prompt": f"Describe the {topics[0]} aspects of {title}. 2 paragraphs."},
                    {"title": f"{core[-1]} Overview", "prompt": f"Describe the {topics[-1]} aspects of {title}. 2 paragraphs."},
                ],
            },
            {"title": "Requirements", "prompt": f"List the key requirements of {title}, grouped as a table with priority."},
            {"title": "Risks and Mitigations", "prompt": f"Identify the top risks for {title} and a mitigation for each."},
            {"title": "Conclusion", "prompt": f"Summarize {title} and list concrete next steps."},
        ]
        import json

        return json.dumps({"title": title, "description": f"Auto-generated outline for: {request[:160]}", "sections": sections})

    def _writer(self, user: str) -> str:
        section = _field(user, "SECTION TITLE", "Overview")
        doc = _field(user, "DOCUMENT TITLE", "the document")
        brief = _field(user, "SECTION GOAL", "")
        topic = section.lower()
        return f"""{_MARK}
This section covers **{section}** for {doc}. {brief or f'It describes the {topic} aspects in practical terms, with an emphasis on clarity and actionability.'}

The approach is organized around three ideas. First, the goals are stated explicitly so every stakeholder shares the same definition of success. Second, the design favors simple, verifiable mechanisms over clever ones. Third, progress is measured continuously so problems surface early.

- Clear ownership: every workstream has a single accountable owner.
- Incremental delivery: value ships in small, reviewable increments.
- Evidence over opinion: decisions cite data, prior art, or user research.

| Aspect | Current state | Target |
| --- | --- | --- |
| Definition | Drafted | Reviewed & approved |
| Coverage | Core topics | All edge cases |
| Validation | Self-review | Cross-team review |

In summary, {topic} is treated as a first-class concern throughout {doc}, and the next sections build directly on the foundations laid out here."""

    def _refiner(self, user: str) -> str:
        action = _field(user, "ACTION", "improve")
        m = re.search(r"TEXT START\n(.*?)\nTEXT END", user, flags=re.DOTALL)
        text = (m.group(1).strip() if m else user.strip())
        if action == "shorten":
            sentences = re.split(r"(?<=[.!?])\s+", text)
            return " ".join(sentences[: max(1, len(sentences) // 2)])
        if action == "expand":
            return text + "\n\nIn practice, this means teams should document assumptions, review them regularly, and adjust course as evidence accumulates. Concrete examples and measurable criteria make the guidance actionable rather than aspirational."
        if action == "summarize":
            lines = [p.strip().split(". ")[0] + "." for p in text.split("\n\n") if p.strip()]
            return "\n".join(f"- {line}" for line in lines[:4])
        if action == "continue":
            return "Building on this foundation, the next step is to validate these assumptions with real users and fold the findings back into the document."
        if action == "fix_grammar":
            return text
        if action == "translate":
            lang = _field(user, "TARGET LANGUAGE", "English")
            return f"[{lang}] {text}"
        if action == "explain":
            sentences = re.split(r"(?<=[.!?])\s+", text)
            key_concepts = [s.strip() for s in sentences[:5] if s.strip()]
            explanation = "## Detailed Explanation\n\n"
            for i, concept in enumerate(key_concepts, 1):
                explanation += f"**{i}.** {concept}\n\n"
            explanation += (
                "This section covers the core ideas above in a structured way. "
                "Each point builds on the previous one to form a coherent understanding "
                "of the topic. In practice, teams should review these concepts carefully "
                "and adapt them to their specific context."
            )
            return explanation
        register = {
            "professional": "From a professional standpoint",
            "friendly": "Here's the friendly version",
            "academic": "From an academic perspective",
            "legal": "Pursuant to the foregoing",
        }.get(action)
        if register:
            return f"{register}, {text[0].lower() + text[1:] if text else text}"
        return text  # rewrite / improve

    def _validator(self, user: str) -> str:
        import json

        return json.dumps({
            "is_valid": True,
            "summary": "No structural issues found (offline demo provider).",
            "issues": [],
        })

    def _reviewer(self, user: str) -> str:
        import json

        words = len(user.split())
        score = min(92, 55 + words // 40)
        titles = re.findall(r"^SECTION:\s*(.+)$", user, flags=re.MULTILINE)[:3]
        focus = titles[0] if titles else "the introduction"
        return json.dumps({
            "overall_score": score,
            "readability": min(95, score + 3),
            "completeness": max(40, score - 8),
            "confidence": 62,
            "summary": "Solid draft with a clear structure; depth varies across sections (offline demo provider).",
            "strengths": [
                "Clear hierarchical structure that is easy to navigate.",
                f"'{focus}' frames the topic well for its audience.",
                "Consistent, professional tone throughout.",
            ],
            "suggestions": [
                f"Add concrete acceptance criteria to '{focus}'.",
                "Support key claims with data or citations.",
                "Break paragraphs longer than five sentences into lists.",
                "Add a short summary table for cross-section metrics.",
            ],
        })

    def _exporter(self, user: str) -> str:
        doc = _field(user, "DOCUMENT TITLE", "This document")
        return (
            f"{doc} presents a complete, structured treatment of its subject: it frames the "
            f"problem, details the approach, and closes with risks and next steps. It is written "
            f"for professional reviewers who need to understand and approve the proposal quickly.\n\n"
            f"- Structured, section-by-section coverage with clear ownership\n"
            f"- Actionable requirements and measurable success criteria\n"
            f"- Explicit risks with mitigations and a concrete path forward"
        )

    # -- LLMProvider interface ------------------------------------------------

    async def complete(
        self, messages: list[LLMMessage], *, temperature: float, max_tokens: int
    ) -> LLMResponse:
        text = self._respond(messages)
        return LLMResponse(text=text, model="mock-offline", latency_ms=1)

    async def stream(
        self, messages: list[LLMMessage], *, temperature: float, max_tokens: int
    ) -> AsyncIterator[str]:
        for word in self._respond(messages).split(" "):
            await asyncio.sleep(0.005)
            yield word + " "
